name: "tnipv"
description: "Run tnipv, the TNIP validator, as a GitHub action"
inputs:
  token:
    description: "GitHub Secret Token"
    required: true
  path:
    description: "Path prefix to watch for changed files"
    required: false
    default: "TNIPS/"
  unchecked:
    description: "TNIP numbers (comma separated) for linter to skip"
    required: false
    default: ""
  deny-checks:
    description: "Replace these checks with errors"
    required: false
    default: ""
  warn-checks:
    description: "Replace these checks with warnings"
    required: false
    default: ""
  allow-checks:
    description: "Hide these checks"
    required: false
    default: ""
  options-file:
    description: "Path to TOML configuration file"
    required: false
    default: ""
runs:
  using: "node20"
  main: "dist/index.js"
